### ISSUE TITLE
Nice tool... Impossible to compile it HAHA

### ISSUE THREAD

**Issue by gabjohn3** [dmaivel/covirt#1]
Dammn bro i really wanted to compile your tool but i never acomplish that
i think is a very good tool
but cant compile it

**Comment by dmaivel** [comment]
Fixed an issue related to LIEF and the RNG implementation, could you try compiling again?

**Comment by gabjohn3** [comment]
Having several issues trying with vs 2019, can u provide a pre compiled version in releases or something ? :D thanks in advance bro

**Comment by dmaivel** [comment]
Sorry, I don't intend on providing binaries; the build instructions are pretty clear and I added a note in the README about compiling with Visual Studio. If issues still persist, it would be more helpful if you could provide more information like build logs, or use Cygwin.
